### ISSUE TITLE
Add server-side prerendering

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#169]
When dealing with multiple versions of docs, we likely only want to support prerendering the `latest/` version.

**Comment by amcdnl** [comment]
I attempted to add app-shell rendering for PWA enhancement using ngu-app-shell, however encountered errors when trying to build.

```
> ngu-app-shell --module src/app/app-module.ts --out dist/index-shell.html

Unhandled Promise rejection: ENOENT: no such file or directory, open 'footer.html' ; Zone: <root> ; Task: Promise.then ; Value: { Error: ENOENT: no such file or directory, open 'footer.html'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at /Users/dev/material.angular.io/node_modules/ng-pwa-tools/lib/common/ng.js:24:24
    at new ZoneAwarePromise (/Users/dev/material.angular.io/node_modules/zone.js/dist/zone-node.js:834:29)
    at FileLoader.get (/Users/dev/material.angular.io/node_modules/ng-pwa-tools/lib/common/ng.js:23:16)
    at DirectiveNormalizer._fetch (/Users/dev/material.angular.io/node_modules/@angular/compiler/bundles/compiler.umd.js:14095:43)
    at DirectiveNormalizer.normalizeTemplateOnly (/Users/dev/material.angular.io/node_modules/@angular/compiler/bundles/compiler.umd.js:14138:29)
    at DirectiveNormalizer.normalizeTemplate (/Users/dev/material.angular.io/node_modules/@angular/compiler/bundles/compiler.umd.js:14122:36)
    at CompileMetadataResolver.loadDirectiveMetadata (/Users/dev/material.angular.io/node_modules/@angular/compiler/@angular/compiler.es5.js:15121:44)
    at /Users/dev/material.angular.io/node_modules/@angular/compiler/@angular/compiler.es5.js:26692:66
```

**Comment by jelbourn** [comment]
The real problem blocking the use of platform-server here is our use of `scss` in `styleUrls` (which `ngc` cannot underatand).

**Comment by amcdnl** [comment]
@jelbourn - So in the past, I've gotten around this by pre-compiling the css and copying the code to a temp dir and replacing `scss` to `css`. Would you be ok w/ an approach like that?

**Comment by jelbourn** [comment]
Not sure it's worth it at the moment. I think we'd get more benefit from lazy loading, which is a harder problem.

**Comment by Splaktar** [comment]
There are more options for this today.

- https://github.com/chrisguttandin/angular-prerender is available for use with Angular Universal for prerendering sites using Guess.js
- Angular version 9 brings an updated Angular Universal which leverages Guess.js and does prerendering. Unfortunately, this doesn't appear to be documented in the [Universal Guide](https://next.angular.io/guide/universal) yet.

**Comment by Splaktar** [comment]
[Scully](https://scully.io) is another option for pre-rendering.
