### ISSUE TITLE
examples module missing-error

### ISSUE THREAD

**Issue by piyush100k** [angular/material.angular.io#264]
ERROR in /home/scideas/ang_test/material.angular.io/src/app/shared/example-viewer/example-viewer.ts (5,47): Cannot find module '@angular/material-examples'.
ERROR in /home/scideas/ang_test/material.angular.io/src/app/shared/plunker/plunker-writer.ts (3,27): Cannot find module '@angular/material-examples'.
ERROR in /home/scideas/ang_test/material.angular.io/src/app/shared/plunker/plunker-button.ts (3,27): Cannot find module '@angular/material-examples'.
ERROR in /home/scideas/ang_test/material.angular.io/src/app/app-module.ts (9,29): Cannot find module '@angular/material-examples'.
ERROR in /home/scideas/ang_test/material.angular.io/src/app/pages/component-viewer/component-viewer.spec.ts (7,34): Cannot find module '@angular/material-examples'.
ERROR in /home/scideas/ang_test/material.angular.io/src/app/shared/example-viewer/example-viewer.spec.ts (4,34): Cannot find module '@angular/material-examples'.
ERROR in /home/scideas/ang_test/material.angular.io/src/app/shared/plunker/plunker-writer.spec.ts (8,27): Cannot find module '@angular/material-examples'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve @angular/material-examples relative to /home/scideas/ang_test/material.angular.io/src/app/app-module.ts., resolving symbol AppModule in /home/scideas/ang_test/material.angular.io/src/app/app-module.ts, resolving symbol AppModule in /home/scideas/ang_test/material.angular.io/src/app/app-module.ts
    at Error (native)
    at syntaxError (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
    at simplifyInContext (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler/bundles/compiler.umd.js:24949:23)
    at StaticReflector.simplify (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler/bundles/compiler.umd.js:24961:13)
    at StaticReflector.annotations (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler/bundles/compiler.umd.js:24391:41)
    at _getNgModuleMetadata (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/scideas/ang_test/material.angular.io/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/scideas/ang_test/material.angular.io/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/scideas/ang_test/material.angular.io/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
please help

**Comment by Chan4077** [comment]
Try running this command (this fixed the problem for me):

```bash
npm run fetch-local
```

**Comment by piyush100k** [comment]
hi chan,
I am sorry its still not working

**Comment by josephperrott** [comment]
@piyush100k 

Do you have both `@angular/material.angular.io` and `@angular/material2` (or forks of them) cloned locally?  You will want both of them cloned locally so that `@angular/material.angular.io` can fetch from `@angular/material2`

`@angular/material-examples` is loaded locally from src/app/share/...

**Comment by piyush100k** [comment]
@josephperrott 
sorry I did that its still not working..
I think developers will be able to understand the problem if they clone the repository and run npm install command..it shows error both on Linux and windows systems.
thanks in advance for your precious time..

**Comment by willshowell** [comment]
@piyush100k I just did the following and everything worked fine:

1. clone/fork `@angular/material2` and `npm install`
2. checkout `2.0.0-beta.10` tag
3. clone/fork `@angular/material.angular.io` and `npm install`
4. run `npm run fetch-local`
5. run `npm start`

**Comment by piyush100k** [comment]
hay pal,
i installed _gulp cli_ and then did all those steps
everything was fine.. it served on port
but with 
 **Warnings while compiling.**
./~/@angular/material-examples/esm5/material-examples.es5.js
60:20-35 "export 'MdStepperModule' was not found in '@angular/material'

**

> and errors on console

**
Uncaught Error: Unexpected value 'undefined' exported by the module 'ExampleMaterialModule'
    at syntaxError (http://localhost:4200/vendor.bundle.js:42123:34)
    at http://localhost:4200/vendor.bundle.js:55829:40
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:55827:49)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary (http://localhost:4200/vendor.bundle.js:55740:52)
    at http://localhost:4200/vendor.bundle.js:55813:72
    at Array.forEach (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:55798:49)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleSummary (http://localhost:4200/vendor.bundle.js:55740:52)
    at http://localhost:4200/vendor.bundle.js:55813:72

**Comment by willshowell** [comment]
@piyush100k I ran into the same thing and resolved it by making sure my material2 clone was checked out on the `2.0.0-beta.10` tag, not `master`.

**Comment by josephperrott** [comment]
Yes, until the next release the docs repo will not build properly without checking out either from the `master` tag as mentioned, or to switch to `angular/material-builds` and `angular/cdk-builds`

**Comment by piyush100k** [comment]
@willshowell @josephperrott 
thanks for your help.. It was solved by
1. installing `gulp cli`
2.clone/fork `@angular/material2` and `npm install`
3.checkout `2.0.0-beta.10 tag`
4. clone/fork @angular/material.angular.io and npm install
5. run` npm run fetch-local`
6. run `npm start`

**Comment by kuncevic** [comment]
Interesting when running `npm run fetch-local` getting `material2\src\material-examples\example-module.ts` checked out and imports pathes changed like
`import {AutocompleteDisplayExample} from './autocomplete-display/autocomplete-display-example'; `changed to 
`import {AutocompleteDisplayExample} from './autocomplete-displayautocomplete-display-example';`

All the rest imports paths from `example-module.ts` getting altered the same way, so had to manually `git checkout example-module.ts` to succeed.

**Comment by idododu** [comment]
for windows user, install Cygwin to run shell scripts.
And do not forget set PATH environment variables. or you can alter package.json, fetch-local script to 
```
PATH=\"D:/Program Files/cygwin/bin;%PATH%\" && bash ./tools/fetch-assets-local.sh
```

without this setting, you will get below errors:
```
'bash' is not recogized as an internal or external command

find parameter format not correct
```

**Comment by s0ftimage** [comment]
wow, install Cygwin.  Would have been so much easier if I could just run npm install @angular/material-examples.  NPM is overrated anyway; what a silly idea.

**Comment by s0ftimage** [comment]
Thanks Idododu, you saved the month.

**Comment by s0ftimage** [comment]
For Windows users, attached file replaces material.angular.io\tools\fetch-assets-local.sh
Edit the file and update the folder locations
Rename the file from .txt to .bat
run the batch file


[copy examples from material2.txt](https://github.com/angular/material.angular.io/files/2104693/copy.examples.from.material2.txt)

**Comment by s0ftimage** [comment]
Also for your Angular.json (twice in same file)

              {
                "input": "src/assets/custom-themes/pink-bluegrey.scss",
                "lazy": true,
                "bundleName": "pink-bluegrey"
              },
              {
                "input": "src/assets/custom-themes/deeppurple-amber.scss",
                "lazy": true,
                "bundleName": "deeppurple-amber"
              },
              {
                "input": "src/assets/custom-themes/indigo-pink.scss",
                "lazy": true,
                "bundleName": "indigo-pink"
              },
              {
                "input": "src/assets/custom-themes/purple-green.scss",
                "lazy": true,
                "bundleName": "purple-green"
              }
