### ISSUE TITLE
'npm run fetch-local' altering the 'material2\src\material-examples\example-module.ts'

### ISSUE THREAD

**Issue by kuncevic** [angular/material.angular.io#268]
Interesting. when running `npm run fetch-local` getting `material2\src\material-examples\example-module.ts` checked out and imports pathes changed like

`import {AutocompleteDisplayExample} from './autocomplete-display/autocomplete-display-example'; `
to 
`import {AutocompleteDisplayExample} from './autocomplete-displayautocomplete-display-example';`

All the rest imports paths from `example-module.ts` getting altered the same way, 

![image](https://user-images.githubusercontent.com/1283734/30679075-1bfd0836-9eda-11e7-877b-083e4f2b3e87.png)

That causing an errors like
```
Error at C:/temp/material2/src/material-examples/example-module.ts:62:46: 
Cannot find module './progress-spinner-overviewprogress-spinner-overview-example'.
Error at C:/temp/material2/src/material-examples/example-module.ts:63:35: 
Cannot find module './radio-ng-modelradio-ng-model-example'.
Error at C:/temp/material2/src/material-examples/example-module.ts:64:36: 
Cannot find module './radio-overviewradio-overview-example'
...
```

So had to manually `git checkout example-module.ts` when `npm run fetch-local` is still running to succeed.

I am building the thing from `cygwin` on my Windows dev PC

**UPDATE0:**
After some investigation I realized that `(cd ${baseSrcPath} && gulp docs)` is causing the problem.
So if even I just run `gulp docs` from `material2` folder the `example-module.ts` gets altered as I explained above.

**UPDATE1:**
The `gulp docs`  running `build-examples-module` task from `examples.ts` so the issue somewhere in this one as if I just run `gulp build-examples-module` the `example-module.ts` gets altered as above and it does not matter if I am running the gulp task form `cygwin` or form any other command line e.g `cmder`, `cmd` or `powershell`

**Comment by kuncevic** [comment]
Just realized that `gulp docs` is causing that problem

**Comment by kuncevic** [comment]
As I am not on the latest head so was missing this commit https://github.com/kuncevic/material2/commit/950edccbc4fdd7b61278629f2bb9b3b1016aff73 that actually fixed the forward  `.replace(/\\/g, '/')`
