### ISSUE TITLE
stackblitzExampleAssetsPath is undefined and overviewPath is nonexistent

### ISSUE THREAD

**Issue by SamuelMarks** [angular/material.angular.io#357]
Error I get on clean repo after `npm i`:
```
$ npm run publish-dev

> material-angular-io@0.0.0 publish-dev material.angular.io
> npm run build-themes && ng build --aot --prod && firebase use material2-docs-dev && firebase deploy


> material-angular-io@0.0.0 build-themes material.angular.io
> bash ./tools/build-themes.sh

Building custom theme scss files.
Finished building CSS.
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (material.angular.io/node_modules/html-webpack-plugin/lib/compiler.js:11:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (material.angular.io/node_modules/html-webpack-plugin/index.js:7:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

Error I get on clean repo—without `npm i`—from `yarn`:
```
$ yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
warning firebase-tools > universal-analytics > node-uuid@1.4.8: Use uuid module instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@angular/cli > @angular-devkit/schematics > @schematics/schematics@0.0.11" has unmet peer dependency "@angular-devkit/core@0.0.22".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ webdriver-manager update && bash ./tools/fetch-assets.sh
webdriver-manager: using local installed version 12.0.2
[23:54:12] I/file_manager - creating folder material.angular.io/node_modules/webdriver-manager/selenium
[23:54:13] I/downloader - curl -o material.angular.io/node_modules/webdriver-manager/selenium/chromedriver_2.34.zip https://chromedriver.storage.googleapis.com/2.34/chromedriver_mac64.zip
[23:54:13] I/downloader - curl -o material.angular.io/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.8.1.jar https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.1.jar
[23:54:13] I/update - chromedriver: unzipping chromedriver_2.34.zip
[23:54:13] I/update - chromedriver: setting permissions to 0755 for material.angular.io/node_modules/webdriver-manager/selenium/chromedriver_2.34
[23:54:16] I/downloader - curl -o material.angular.io/node_modules/webdriver-manager/selenium/geckodriver-v0.19.1.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-macos.tar.gz
[23:54:18] I/update - geckodriver: unzipping geckodriver-v0.19.1.tar.gz
[23:54:18] I/update - geckodriver: setting permissions to 0755 for material.angular.io/node_modules/webdriver-manager/selenium/geckodriver-v0.19.1
Cloning into '/tmp/material-assets'...
remote: Counting objects: 1000, done.
remote: Compressing objects: 100% (753/753), done.
remote: Total 1000 (delta 389), reused 591 (delta 225), pack-reused 0
Receiving objects: 100% (1000/1000), 490.12 KiB | 772.00 KiB/s, done.
Resolving deltas: 100% (389/389), done.
cp: cannot stat '/tmp/material-assets/overview': No such file or directory
cp: missing destination file operand after '/tmp/material-assets/stackblitz/examples'
Try 'cp --help' for more information.
✨  Done in 148.17s.
```

Versions:
```
node 8.9.3
yarn 1.3.2
npm 5.5.1
```

**Comment by SamuelMarks** [comment]
`stackblitzExampleAssetsPath` is never defined.  @amcdnl / @jelbourn what is this value meant to be?

That variable is used but never defined, as of latest commit: [tools/fetch-assets.sh](https://github.com/angular/material.angular.io/blob/f775248067ac1076b14fbe5cee3a955f9c4e637e/tools/fetch-assets.sh)

Was it just:
```bash
stackblitzExamplesPath=${tmpAssetClonePath}/stackblitz/assets
```

?

**Comment by jelbourn** [comment]
Docs content needs to be fetched separately with the `fetch-asshets.sh` script (or the local version). The non-local one might actually be broken right now.

**Comment by SamuelMarks** [comment]
So we are not meant to follow the README.md and use `npm run publish-dev` then?

**Comment by jelbourn** [comment]
Those commands are for our own testing/use. You won't have permission to deploy to our dev instance.

**Comment by SamuelMarks** [comment]
Maybe a mention of this (in parentheses) in the heading?

>##Deployment instructions (@ Google)

**Comment by SamuelMarks** [comment]
Wait I just saw a commit: https://github.com/angular/material.angular.io/commit/3f1ff3bb62b89af35f0563b40cc2f6ad7b06af7a
