### ISSUE TITLE
setup instruction in `readme.md` no longer works

### ISSUE THREAD

**Issue by JiboStore** [angular/material.angular.io#425]
I cloned `master` and run the setup according to instructions on `readme` but it gives me error:

```
npm ERR! material-angular-io@0.0.0 publish-dev: `bash ./tools/deploy.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-angular-io@0.0.0 publish-dev script 'bash ./tools/deploy.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the material-angular-io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bash ./tools/deploy.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs material-angular-io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls material-angular-io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Development\github\angular-mine\angular-material-docs\npm-debug.log
```

here is the npm_debug.log

```
11 silly lifecycle material-angular-io@0.0.0~publish-dev: Args: [ '/d /s /c', 'bash ./tools/deploy.sh' ]
12 silly lifecycle material-angular-io@0.0.0~publish-dev: Returned: code: 1  signal: null
13 info lifecycle material-angular-io@0.0.0~publish-dev: Failed to exec publish-dev script
14 verbose stack Error: material-angular-io@0.0.0 publish-dev: `bash ./tools/deploy.sh`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (G:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (G:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid material-angular-io@0.0.0
```

I have been asking around in angular-material2's Gitter chat, but seems like this is specific to this documentation repo. My other angular projects and angular material project works fine..

**Comment by Splaktar** [comment]
Right, you shouldn't try to run the `Deployment instructions` in the README.

You need to do

- `npm i`
- `npm run fetch-local`
- `npm start`
